//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Inventory : DBConnection
{
	public virtual int On_Hand
	{
		get;
		set;
	}

	public virtual int Inventory_id
	{
		get;
		set;
	}

	public virtual string Product
	{
		get;
		set;
	}

	public virtual int Reorder_Level
	{
		get;
		set;
	}

	public virtual int Reorder_Quantity
	{
		get;
		set;
	}

	public virtual int On_Order
	{
		get;
		set;
	}

	public virtual void ToString()
	{
		throw new System.NotImplementedException();
	}

	public virtual void setFiltersToOrder()
	{
		throw new System.NotImplementedException();
	}

	public Inventory()
	{
	}

	private Inventory()
	{
	}

	public virtual void ModifyItemStock(int newStockValue)
	{
		throw new System.NotImplementedException();
	}

	public virtual void UpdateReorderQuantity()
	{
		throw new System.NotImplementedException();
	}

	public virtual void UpdateReorderLevel()
	{
		throw new System.NotImplementedException();
	}

	public virtual void UpdateOnOrderQuantity()
	{
		throw new System.NotImplementedException();
	}

	public virtual void UpdateProductLocation()
	{
		throw new System.NotImplementedException();
	}

	public virtual void Save()
	{
		throw new System.NotImplementedException();
	}

	public virtual void Get(int( Inventory_Id)
	{
		throw new System.NotImplementedException();
	}

	public virtual void GetAll()
	{
		throw new System.NotImplementedException();
	}

	public virtual void GetWithCode(string Product_Code)
	{
		throw new System.NotImplementedException();
	}

	public virtual void GetWithName(string Product)
	{
		throw new System.NotImplementedException();
	}

	public virtual void Get(string Product_Location)
	{
		throw new System.NotImplementedException();
	}

}

