//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class OrderStatus : DBConnection
{
	public virtual int OrderStatus_Id
	{
		get;
		set;
	}

	public virtual string Status_Text
	{
		get;
		set;
	}

	public virtual void GetAll()
	{
		throw new System.NotImplementedException();
	}

	public OrderStatus()
	{
	}

	private OrderStatus()
	{
	}

}

