//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Orders : DBConnection
{
	public virtual int Order_Id
	{
		get;
		set;
	}

	public virtual DateTime Order_Date
	{
		get;
		set;
	}

	public virtual string Employee
	{
		get;
		set;
	}

	public virtual string Shipping_Address
	{
		get;
		set;
	}

	public virtual string Ship_City
	{
		get;
		set;
	}

	public virtual string Ship_State
	{
		get;
		set;
	}

	public virtual int Zip
	{
		get;
		set;
	}

	public virtual double Order_Total
	{
		get;
		set;
	}

	public virtual string Status
	{
		get;
		set;
	}

	public virtual DateTime Closed_Date
	{
		get;
		set;
	}

	public virtual void ToString()
	{
		throw new System.NotImplementedException();
	}

	public virtual void CompleteOrder()
	{
		throw new System.NotImplementedException();
	}

	private Orders()
	{
	}

	public Orders()
	{
	}

	public virtual void Save()
	{
		throw new System.NotImplementedException();
	}

	public virtual void Get(int Order_Id)
	{
		throw new System.NotImplementedException();
	}

	public virtual void GetAll()
	{
		throw new System.NotImplementedException();
	}

}

