//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class ProductLocations : DBConnection
{
	public virtual int Location_Id
	{
		get;
		set;
	}

	public virtual string Product_Location
	{
		get;
		set;
	}

	public virtual int Product_Quantity
	{
		get;
		set;
	}

	public virtual string Product_Code
	{
		get;
		set;
	}

	public ProductLocations()
	{
	}

	private ProductLocations()
	{
	}

	public virtual void Save()
	{
		throw new System.NotImplementedException();
	}

	public virtual void Get(int Location_Id)
	{
		throw new System.NotImplementedException();
	}

	public virtual void GetAll()
	{
		throw new System.NotImplementedException();
	}

	public virtual void ToString()
	{
		throw new System.NotImplementedException();
	}

	public virtual void ChangeItemAtLocation(int Location_Id, string Product_Code)
	{
		throw new System.NotImplementedException();
	}

	public virtual void RemoveItemAtLocation(int Location_Id)
	{
		throw new System.NotImplementedException();
	}

}

