//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Product : DBConnection
{
	public virtual string Product_Name
	{
		get;
		set;
	}

	public virtual string Product_Code
	{
		get;
		set;
	}

	public virtual bool Discontinue
	{
		get;
		set;
	}

	public virtual string Category
	{
		get;
		set;
	}

	public virtual int Product_Id
	{
		get;
		set;
	}

	public virtual double List_Price
	{
		get;
		set;
	}

	public virtual double Unit_Cost
	{
		get;
		set;
	}

	public virtual void ToString()
	{
		throw new System.NotImplementedException();
	}

	public Product()
	{
	}

	private Product()
	{
	}

	public virtual void Save()
	{
		throw new System.NotImplementedException();
	}

	public virtual void Get(int Product_Id)
	{
		throw new System.NotImplementedException();
	}

	public virtual void GetAll()
	{
		throw new System.NotImplementedException();
	}

	public virtual void DiscontinueItem()
	{
		throw new System.NotImplementedException();
	}

	public virtual void UpdateListPrice(int Product_Id, double List_Price)
	{
		throw new System.NotImplementedException();
	}

	public virtual void ChangeProductCategory(int Product_Id, string Category)
	{
		throw new System.NotImplementedException();
	}

}

