//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Purchase Order : DBConnection
{
	public virtual int PurchaseOrders_Id
	{
		get;
		set;
	}

	public virtual DateTime Order_Date
	{
		get;
		set;
	}

	public virtual string Created_By
	{
		get;
		set;
	}

	public virtual DateTime Created_Date
	{
		get;
		set;
	}

	public virtual double Shipping_Fee
	{
		get;
		set;
	}

	public virtual double Tax
	{
		get;
		set;
	}

	public virtual DateTime Payment_Date
	{
		get;
		set;
	}

	public virtual Double Payment_Amount
	{
		get;
		set;
	}

	public virtual double Order_Subtotal
	{
		get;
		set;
	}

	public virtual double Order_Total
	{
		get;
		set;
	}

	public virtual DateTime Date_Received
	{
		get;
		set;
	}

	public virtual string Status
	{
		get;
		set;
	}

	public virtual void ToString()
	{
		throw new System.NotImplementedException();
	}

	public virtual void PurchaseOrder()
	{
		throw new System.NotImplementedException();
	}

	private void PurchaseOrder()
	{
		throw new System.NotImplementedException();
	}

	public virtual void CompleteOrder()
	{
		throw new System.NotImplementedException();
	}

	public virtual void Save()
	{
		throw new System.NotImplementedException();
	}

	public virtual void Get(int) PurchaseOrders_Id)
	{
		throw new System.NotImplementedException();
	}

	public virtual void GetAll()
	{
		throw new System.NotImplementedException();
	}

}

